name: rhtml5
description: Render HTML source as native flutter widgets
version: 0.0.1+1
homepage: https://github.com/rey-xi/html5
repository: https://github.com/rey-xi/html5

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  html: ^0.15.1
  csslib: ^0.17.2
  qp_xt: ^0.0.1+7

  list_counter: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0

flutter: